add Add Strings
tkkawa/leetcode pull request #62
Opened 2021-04-03 06:18 UTC by tkkawa

Please check my code.

2021-04-03 12:34 UTC, ryuji0123 requested changes
See this:

Follow up: Could you solve it without using any built-in BigInteger library or converting the inputs to integer directly?

2021-04-04 03:47 UTC, ryuji0123 requested changes
Basically, you should avoid complex codes.
See solution in leetcode

2021-04-04 03:47 UTC, ryuji0123 commented on 415_add-strings.py
> +            for i in range(len(res), len(res)+max(len(lis1), len(lis2))-min(len(lis1), len(lis2))):
too difficult to understand

2021-04-04 09:42 UTC, tkkawa commented
It's solution in leetcode.

2021-04-11 09:17 UTC, ryuji0123 requested changes
Check your coding style before creating PR

2021-04-11 09:17 UTC, ryuji0123 commented on 415_add-strings.py
> +        total1 = ord(num1[0])-48
avoid using magic number (in this case, 48's meaning is very unclear) again.

2021-04-11 09:17 UTC, ryuji0123 commented on 415_add-strings.py
> +        total = total1+total2
See Google style before creating PR
```
total = total1 + total2
```

2021-04-11 09:17 UTC, ryuji0123 commented on 415_add-strings.py
> +            total1 = total1*10+num
See PEP8: Whitespace in Expressions and Statements

total1 = total1*10 + num

2021-04-12 03:57 UTC, ryuji0123 requested changes

2021-04-12 03:57 UTC, ryuji0123 commented on 415_add-strings.py
> +            total2 = total2 * 10+num
See https://www.python.org/dev/peps/pep-0008/#other-recommendations
total2 = total2*10 + num

2021-04-12 03:57 UTC, ryuji0123 commented on 415_add-strings.py
> +            total1 = total1 * 10 + num
See https://www.python.org/dev/peps/pep-0008/#other-recommendations
 total1 = total1*10 + num

2021-04-15 14:29 UTC, ryuji0123 approved these changes
LGTM

2021-04-17 12:58 UTC, merged