add Partition Array Into Three Parts With Equal Sum
tkkawa/leetcode pull request #64
Opened 2021-04-04 09:33 UTC by tkkawa

Please check my code.

2021-04-05 02:48 UTC, ryuji0123 requested changes
Very close

2021-04-05 02:48 UTC, ryuji0123 commented on 1013_partition-array-into-three-parts-with-equal-sum.py
> +        sub_sum = sum(arr) / 3
to make sure sub_sum is int, write like:

```py
sub_sum = sum(arr) // 3
```

2021-04-05 02:48 UTC, ryuji0123 commented on 1013_partition-array-into-three-parts-with-equal-sum.py
> +        for i in range(len(arr)):
if you don't update elements in arr and just add them to sub, you should write like:

```py
for num in arr:
    sub += num
```

2021-04-05 02:48 UTC, ryuji0123 commented on 1013_partition-array-into-three-parts-with-equal-sum.py
> +        if a > 2:
```py
if 2 < a:
```

2021-04-05 02:48 UTC, ryuji0123 commented on 1013_partition-array-into-three-parts-with-equal-sum.py
> +        if a > 2:
Also, you should return True or False more clearly

```py
return 2 < a
```

2021-04-05 12:50 UTC, ryuji0123 requested changes
see my comments

2021-04-05 12:50 UTC, ryuji0123 commented on 1013_partition-array-into-three-parts-with-equal-sum.py
> +        sub_sum = sum(arr) / 3
You miss this:
```py
sub_sum = sum(arr) // 3
```

2021-04-05 12:57 UTC, tkkawa commented
if sub_sum is int, 11th line is bad.
For example, when input is [1,1,1,1], output is true, but  true solution is false.

2021-04-05 12:59 UTC, ryuji0123 commented
use divmod

```py
sub_sum, m = divmod(sum(arr), 3)
if m != 0:
    return False
```

2021-04-07 00:56 UTC, ryuji0123 approved these changes
LGTM

2021-04-08 14:08 UTC, merged